// <auto-generated />
using ECommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceApp.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200423221036_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceApp.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Initial Evaluation where physical therapist will spend time with you to learn about your condition, your previous level of function, and how your condition is affecting your life.",
                            Duration = "1 hour",
                            Price = 100.00m,
                            ServiceType = "Initial Consultation"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Follow up evaluation.",
                            Duration = "30 minutes",
                            Price = 50.00m,
                            ServiceType = "Follow-up Consultation"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Lower back stuff here.",
                            Duration = "30 minutes",
                            Price = 75.00m,
                            ServiceType = "Lower Back Adjustment"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Neck stuff here.",
                            Duration = "45 minutes",
                            Price = 100.00m,
                            ServiceType = "Neck Adjustment"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Upper back stuff here.",
                            Duration = "30 minutes",
                            Price = 75.00m,
                            ServiceType = "Upper Back Adjustment"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Package deal lower back stuff here.",
                            Duration = "1 hour 30 minutes",
                            Price = 100.00m,
                            ServiceType = "Pack of Lower Back Adjustments"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Package deal neck stuff here.",
                            Duration = "1 hour 30 minutes",
                            Price = 125.00m,
                            ServiceType = "Pack of Neck Adjustments"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Package deal lower back stuff here.",
                            Duration = "1 hour 30 minutes",
                            Price = 100.00m,
                            ServiceType = "Pack of Upper Back Adjustments"
                        },
                        new
                        {
                            ID = 9,
                            Description = "60 minute massage description here.",
                            Duration = "60 minutes",
                            Price = 80.00m,
                            ServiceType = "60 Minute Massage"
                        },
                        new
                        {
                            ID = 10,
                            Description = "60 minute massage description here.",
                            Duration = "30 minutes",
                            Price = 45.00m,
                            ServiceType = "30 Minute Massage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
