// <auto-generated />
using System;
using ECommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceApp.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200505034308_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceApp.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ECommerceApp.Models.CartItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServicesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("ServicesID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceApp.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Initial Evaluation where the Chiropractor will spend time with you to learn about your condition, your previous level of function, and how your condition is affecting your life. He will then perform an examination and perform a treatment.",
                            Duration = "1 hour",
                            Image = "/Styles/Assets/InitialEvaluation.jpg",
                            Price = 250.00m,
                            ServiceType = "Initial Consultation"
                        },
                        new
                        {
                            ID = 2,
                            Description = "A Follow-up Evaluation where the Chiropractor will spend time with you to see how you are doing and how you are meeting your functional goals. He will then perform an mini-examination and perform a treatment. Note: This service is only available after you have had a full initial consultation",
                            Duration = "45-60 minutes",
                            Image = "/Styles/Assets/FollowUpConsultation.jpg",
                            Price = 150.00m,
                            ServiceType = "Follow-up Consultation"
                        },
                        new
                        {
                            ID = 3,
                            Description = "A follow up visit for targetted adjustment of the lower back.",
                            Duration = "30 minutes",
                            Image = "/Styles/Assets/LowBack1.jpg",
                            Price = 75.00m,
                            ServiceType = "Lower Back Adjustment"
                        },
                        new
                        {
                            ID = 4,
                            Description = "A follow up visit for targetted adjustment of the neck.",
                            Duration = "30 minutes",
                            Image = "/Styles/Assets/NeckAdjustment1.jpg",
                            Price = 85.00m,
                            ServiceType = "Neck Adjustment"
                        },
                        new
                        {
                            ID = 5,
                            Description = "A follow up visit for targetted adjustment of the upper back/thoracic region.",
                            Duration = "30 minutes",
                            Image = "/Styles/Assets/UpperBack1.jpg",
                            Price = 75.00m,
                            ServiceType = "Upper Back Adjustment"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Reguar adjustments are sometimes necessary to maintain pain free postural alignment. This service allows you to purchase 5 low back adjustments at a discounted rate that may be used within the next 6 months.",
                            Duration = "30 minutes each",
                            Image = "/Styles/Assets/LowBack2.jpg",
                            Price = 300.00m,
                            ServiceType = "5-Pack of Lower Back Adjustments"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Reguar adjustments are sometimes necessary to maintain pain free postural alignment. This service allows you to purchase 5 neck adjustments at a discounted rate that may be used within the next 6 months.",
                            Duration = "30 minutes each",
                            Image = "/Styles/Assets/NeckAdjustment2.jpg",
                            Price = 325.00m,
                            ServiceType = "5-Pack of Neck Adjustments"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Reguar adjustments are sometimes necessary to maintain pain free postural alignment. This service allows you to purchase 5 upper back/thoracic region adjustments at a discounted rate that may be used within the next 6 months.",
                            Duration = "30 minutes each",
                            Image = "/Styles/Assets/UpperBack2.jpg",
                            Price = 300.00m,
                            ServiceType = "5-Pack of Upper Back Adjustments"
                        },
                        new
                        {
                            ID = 9,
                            Description = "A 60-minute Orthopedic massage allowing for deep tissue therapy of problem areas. The massage may incorporate Shiatzu, Swedish or trigger point techniques.",
                            Duration = "60 minutes",
                            Image = "/Styles/Assets/Massage1.jpg",
                            Price = 80.00m,
                            ServiceType = "60 Minute Massage"
                        },
                        new
                        {
                            ID = 10,
                            Description = "A 30-minute Orthopedic massage providing an overall massage. The massage may incorporate Shiatzu or Swedish techniques. This massage is best suited before a Chiropractic adjustment. If you are seeking deep tissue or have a specific problem area, consider a 60-minute massage instead.",
                            Duration = "30 minutes",
                            Image = "/Styles/Assets/Massage2.jpg",
                            Price = 45.00m,
                            ServiceType = "30 Minute Massage"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Models.CartItems", b =>
                {
                    b.HasOne("ECommerceApp.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Models.Inventory", "Services")
                        .WithMany()
                        .HasForeignKey("ServicesID");
                });
#pragma warning restore 612, 618
        }
    }
}
